name: nexcoin
description: "Sample fintech app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  lottie: ^3.1.3

  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  cryptofont: ^1.0.2+1


flutter:
  uses-material-design: true

  assets:
    - assets/memoji.png
    - assets/splash.json
